service: playlists #nombre del servicio

provider:
  name: aws
  runtime: nodejs14.x # versi贸n de Node.js 
  stage: dev
  region: us-east-1 # regi贸n 

functions:
  graphql:
    handler: src/resolvers.Query.playlistByUser # ubicaci贸n del archivo y la funci贸n que maneja GraphQL
    events:
      - http:
          path: /playlist/{id}
          method: GET

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}
